### ISSUE TITLE
Doesn't work with Ballerina 1.1.0

### ISSUE THREAD

**Issue by jpvadell** [wso2-ballerina/module-scim2#54]
**Description:**
The problem is with scim2_endpoint.bal, lines 651 and 652.
Must be in one line...

https://github.com/wso2-ballerina/module-scim2/blob/9ddb094233e9335c23a45c117ce203f3ebe18792/src/scim2/scim2_endpoint.bal#L651

**Comment by anupama-pathirage** [comment]
Closing as we are no longer maintaining this code.
